#!/bin/bash

#PBS -S /bin/bash
#PBS -N matlab
#PBS -o mo.txt
#PBS -j oe
#PBS -l walltime=00:10:00
#PBS -l select=1:ncpus=1
#PBS -q iceq
#PBS -m e -M filippo.gatti@centralesupelec.fr

#chargement des modules
module purge
module load matlab/r2015b

#On se place dans le repertoire depouis lequel le job a ete soumis
cd $PBS_O_WORKDIR
cd /home/gattif/PHD_passing_through_polimi/syn2ann/src/

matlab -nodesktop -nosplash -nodisplay -r 'syn2ann_drive'
