%% *DISPLACEMENT TIME HISTORY*
for i_ = 1:spg(1)
    xpl{i_} = xplot{i_}.mon.vtm{identity}-time_shift(i_);
    ypl{i_} = xplot{i_}.syn{identity}.thd.(cpp)*utd.thd;
    leg(i_) = {legplot(i_)};
end
%
% # _ASIDE_
%
if logical(mod)
    fpplot('xpl',xpl,'ypl',ypl,'pfg',pfg.thd.c,'spg',spg,'pax',pax,...
        'scl',scl.thd,'grd',grd.thd,'mrk',mrkd,'lst',lstd,'lwd',lwdd,...
        'xlm',{xlm.thd},'xlb',xlb.thd,'xtk',{xtk.thd},...
        'ylm',{ylm.thd},'ylb',ylb.thd,'ytk',{ytk.thd},...
        'leg',leg,'tit',std);
else
    fpplot('xpl',xpl,'ypl',ypl,'pfg',pfg.thd.c,'spg',spg,'pax',pax,...
        'scl',scl.thd,'grd',grd.thd,...
        'xlm',{xlm.thd},'xlb',xlb.thd,'xtk',{xtk.thd},...
        'ylm',{ylm.thd},'ylb',ylb.thd,'ytk',{ytk.thd},...
        'leg',leg,'tit',std);
end
saveas(gcf,strcat(fnm,sprintf('_thd_%s',cpp)),'epsc');