%% *FOURIER SPECTRA*
for i_ = 1:spg(1)
    nfr     = numel(xplot{i_}.mon.vfr{identity})/2;
    xpl{i_} = xplot{i_}.mon.vfr{identity}(1:nfr);
    ypl{i_} = abs(xplot{i_}.syn{identity}.fsa.(cpp)(1:nfr))*utd.fsa;
end
leg = {legplot};
if logical(mod)
    fpplot('xpl',xpl,'ypl',ypl,'pfg',pfg.fsa,...
        'scl',scl.fsa,'grd',grd.fsa,'mrk',mrkd,'lst',lstd,'lwd',lwdd,...
        'xlm',{xlm.fsa},'xlb',xlb.fsa,'xtk',{xtk.fsa},...
        'ylm',{ylm.fsa},'ylb',ylb.fsa,'ytk',{ytk.fsa},...
        'leg',leg,'tit',std);
else
    fpplot('xpl',xpl,'ypl',ypl,'pfg',pfg.fsa,...
        'scl',scl.fsa,'grd',grd.fsa,...
        'xlm',{xlm.fsa},'xlb',xlb.fsa,'xtk',{xtk.fsa},...
        'ylm',{ylm.fsa},'ylb',ylb.fsa,'ytk',{ytk.fsa},...
        'leg',leg,'tit',std);
end
obj=get(gcf,'children');
obj(1).Location='southwest';
saveas(gcf,strcat(fnm,sprintf('_fsa_%s',cpp)),'epsc');
