global pfg xlm xlb xtk ylm ylb ytk grd scl tit utd 

for j_ = 1:numel(cpp)
    %% *POST-PROCESS - RECORDS vs PBS*
    set(0,'defaultaxescolororder',rgb('Black'));
    fnm = fullfile(sp,sprintf('%s_rec_%s',st,ann.(cpp{j_}).nl));
    syn2ann_plot_compare([0;0;1;1;1],{rec.org},mm_,dlg(j_),...
        {'REC'},(cpp{j_}),ttt,fnm,0,{'none'},...
        {'-'},2);
    fnm = fullfile(sp,sprintf('%s_pbs_%s',st,ann.(cpp{j_}).nl));
    syn2ann_plot_compare([0;0;1;1;1],{nss.org},mm_,dlg(j_),...
        {'PBS'},(cpp{j_}),ttt,fnm,vtm_shift,{'none'},...
        {'-'},2);
    fnm = fullfile(sp,sprintf('%s_hsp_%s',st,ann.(cpp{j_}).nl));
    syn2ann_plot_compare([0;0;1;1;1],{hbs.sps},mm_,dlg(j_),...
        {'HYB-SP96'},(cpp{j_}),ttt,fnm,vtm_shift,{'none'},...
        {'-'},2);
    fnm = fullfile(sp,sprintf('%s_ssp_%s',st,ann.(cpp{j_}).nl));
    syn2ann_plot_compare([0;0;1;1;1],{spm.sps.(cpp{j_})},mm_,dlg(j_),...
        {'SPM'},(cpp{j_}),ttt,fnm,vtm_shift,{'none'},...
        {'-'},2);
    set(0,'defaultaxescolororder',clr131);
    fnm = fullfile(sp,sprintf('%s_rec_pbs_hsp_ssp_%s',st,ann.(cpp{j_}).nl));
    syn2ann_plot_compare([1;0;0;0;0],{rec.org;nss.sps;hbs.sps;spm.sps.(cpp{j_})},...
        mm_,dlg(j_),{'REC';'PBS';'HYB';'SPM'},(cpp{j_}),ttt,fnm,zeros(1,4),...
        {'none';'none';'none';'none'},...
        {'-';':';'--';'-'},...
        [4,1.5,1,2.5]);
    fnm = fullfile(sp,sprintf('%s_rec_pbs_hsp_ssp_%s',st,ann.(cpp{j_}).nl));
    syn2ann_plot_compare([0;1;0;0;0],{rec.org;nss.sps;hbs.sps;spm.sps.(cpp{j_})},...
        mm_,dlg(j_),{'REC';'PBS';'HYB';'SPM'},(cpp{j_}),ttt,fnm,zeros(1,4),...
        {'none';'none';'none';'none'},...
        {'-';':';'--';'-'},...
        [1,1,1,1]);
end