%% *SA SPECTRA*
for i_ = 1:spg(1)
    xpl{i_} = xplot{i_}.mon.vTn;
    try
        ypl{i_} = abs(xplot{i_}.syn{identity}.psa.(cpp))*utd.psa;
    catch
        disp('PLOTTING GEOEMTRIC MEAN PSA!')
        ypl{i_} = abs(xplot{i_}.syn{identity}.psa.gh)*utd.psa;
    end
end
leg = {legplot};

if logical(mod)
    fpplot('xpl',xpl,'ypl',ypl,'pfg',pfg.psa,...
        'scl',scl.psa,'grd',grd.psa,'mrk',mrkd,'lst',lstd,'lwd',lwdd,...
        'xlm',{xlm.psa},'xlb',xlb.psa,'xtk',{xtk.psa},...
        'ylm',{ylm.psa},'ylb',ylb.psa,'ytk',{ytk.psa},...
        'leg',leg,'tit',std);
else
    fpplot('xpl',xpl,'ypl',ypl,'pfg',pfg.psa,...
        'scl',scl.psa,'grd',grd.psa,...
        'xlm',{xlm.psa},'xlb',xlb.psa,'xtk',{xtk.psa},...
        'ylm',{ylm.psa},'ylb',ylb.psa,'ytk',{ytk.psa},...
        'leg',leg,'tit',std);
end
saveas(gcf,strcat(fnm,sprintf('_psa_%s',cpp)),'epsc');