function [] = GUI_sm_setup()
    global hbs smr Strs out
    %% SPECTRAL MATCHING
    % _spectral scaling_ hybrid synthetics + ANN_
    out=cell(numel(smr.trs),1);
    for i_=1:numel(smr.trs)
        out{i_}=synthetics2ann_spectral_matching(hbs,smr.trs{i_});
    end
    
    Strs.fh(1) = figure('units','pixels',...
        'position',[0 350 320 60],...
        'menubar','none',...
        'name','SPECTRAL MATCHING',...
        'numbertitle','off',...
        'resize','off');
    Strs.pb(1) = uicontrol(Strs.fh(1),'style','push',...
        'units','pix',...
        'position',[5 5 150 50],...
        'fontsize',14,...
        'string','PLOT');
    Strs.pb(2) = uicontrol(Strs.fh(1),'style','push',...
        'units','pix',...
        'position',[160 5 150 50],...
        'fontsize',14,...
        'string','CLOSE');
    
    set(Strs.pb(1:2),'callback',{@pb_call,Strs})  % Set callbacks.
    uiwait(Strs.fh(1)) % Wait for continue or stop button.

    return
end

function [] = pb_call(varargin)
    global out Strs
    % Callback for pushbutton.
    if varargin{1} == Strs.pb(1)
        % Get the structure.
        Strs.fh(2) = figure('units','pixels',...
            'position',[400 300 305 250],...
            'menubar','none',...
            'name','PLOT SPECTRA',...
            'numbertitle','off',...
            'resize','off');
        uicontrol(Strs.fh(2),'style','text','units','pix','position',[5 220 295 25],...
            'string','MONITOR','fontsize',14,'fontweight','bold');
        Strs.lb(1) = uicontrol(Strs.fh(2),'style','list',...
            'units','pix',...
            'position',[5 35 295 180],...
            'fontsize',14,...
            'string',mat2str(mon.id));
        Strs.pb(3) = uicontrol(Strs.fh(2),'style','push',...
            'units','pix',...
            'position',[5 5 95 25],...
            'fontsize',14,...
            'string','PLOT');
        
        set(Strs.pb(4:5),'callback',{@pb0_call,Strs})  % Set callbacks.
        uiwait(Strs.fh(2));
    elseif varargin{1} == Strs.pb(2)  % Get the structure.
        %%
        % _exit_
        if any(smr.status)
            close(Strs.fh(1))  % Found the one we are looking for.
        end
    end
    return
end

function [] = pb0_call(varargin)
    global out Strs
    % Callback for pushbutton.
    if varargin{1} == Strs.pb(3)  % Get the structure.
%         %%
%         % _parse trained ANN network - horizontal directions_
%         [ann.hrz.fn,pt] = uigetfile('*.mat','Select Monitor Metadata File (*.dat): ',...
%             'MultiSelect','off');
%         if ~strcmpi(pt(end),filesep)
%             pt=strcat(pt,filesep);
%         end
%         set(Strs.lb(1),'String',ann.hrz.fn);
%         ann.hrz.fn = fullfile(pt,ann.hrz.fn);
%         ann.hrz.TnC  = GUI_13([500 300 305 120],'CORNER PERIOD',[.01,3],1);
%         ann.status(1) = 1;
    elseif varargin{1} == Strs.pb(4)  % Get the structure.
%         if ann.status(1) == 1;
%             close(Strs.fh(2));
%         end
    end
    return
end