%% *GENERATION OF STRONG GROUND MOTION SIGNALS BY COUPLING PHYSICS-BASED ANALYSIS WITH ARTIFICIAL NEURAL NETWORKS*
% _Editor: Filippo Gatti
% CentraleSupélec - Laboratoire MSSMat
% DICA - Politecnico di Milano
% Copyright 2016_
%% *NOTES*
% _syn2ann_plot_res_station_both_: function to plot syn2ann results at each
% station with both sp96 and exsim hybridization
%% *N.B.*
% Need for:
% _syn2ann_plot_compare.m_

global pfg xlm xlb xtk ylm ylb ytk grd scl mrk tit utd

st = bhr.nm{mm_};
fprintf('%s-with HYBRID\n',bhr.nm{mm_});
dlg = cell(3,1);
dlg{1} = 'EW';
dlg{2} = 'NS';
dlg{3} = 'UD';

for j_ = 1:numel(cpp)
%     %% *POST-PROCESS - RECORDS vs PBS*
%     fnm = fullfile(sp,sprintf('%s_rec_pbs_%s',st,ann.mtd.scl{j_}));
%     % all
%     set(0,'defaultaxescolororder',clr.rec_pbs);
%     syn2ann_plot_compare(...
%         ones(5,1),...
%         {rec.org,nss.org},...
%         mm_,dlg(j_),...
%         {'REC';'PBS'},...
%         (cpp{j_}),bhr.nm{mm_},...
%         fnm,...
%         [0,vtm_shift(2)]);
    
%     %% *POST-PROCESS - RECORDS vs SPECTRAL MATCHED vs ANN*
%     fnm = fullfile(sp,sprintf('%s_rec_ann_BTH_%s',st,ann.mtd.scl{j_}));
%     set(0,'defaultaxescolororder',clr.rec_ann_emp_sto);
%     syn2ann_plot_compare(...
%         [1 0 0 0 0],...
%         {rec.org;spm.sps.(cpp{j_});spm.exs.(cpp{j_});trs.sps.(cpp{j_})},...
%         mm_,dlg(j_),...
%         {'REC';'SPM-SP96';'SPM-EXSIM';'ANN'},...
%         (cpp{j_}),bhr.nm{mm_},...
%         fnm,...
%         zeros(4,1),...
%         {'none';'none';'none';'o'},...
%         {'-';':';'-.';'none'});    
    %% *POST-PROCESS - RECORDS vs PBS vs SPECTRAL MATCHED*
    fnm = fullfile(sp,sprintf('%s_rec_pbs_spm_BTH_%s',st,ann.mtd.scl{j_}));
    set(0,'defaultaxescolororder',clr.rec_pbs_spmemp_spmsto);
    syn2ann_plot_compare(...
        [1 0 0 0 0],...
        {rec.org;nss.org;spm.sps.(cpp{j_});spm.exs.(cpp{j_})},...
        mm_,dlg(j_),...
        {'REC';'PBS';'SPM-SP96';'SPM-EXSIM'},...
        (cpp{j_}),bhr.nm{mm_},...
        fnm,...
        zeros(4,1),...
        {'none';'none';'none';'none'},...
        {'-';'-';'-';':'});   
    syn2ann_plot_compare(...
        [0 1 0 0 0],...
        {rec.org;nss.org;spm.sps.(cpp{j_})},...
        mm_,dlg(j_),...
        {'REC';'PBS';'SPM-SP96'},...
        (cpp{j_}),bhr.nm{mm_},...
        fnm,...
        zeros(4,1),...
        {'none';'none';'none'},...
        {'-';'-';'-'});   
end