%% *GENERATION OF STRONG GROUND MOTION SIGNALS BY COUPLING PHYSICS-BASED ANALYSIS WITH ARTIFICIAL NEURAL NETWORKS*
% _Editor: Filippo Gatti
% CentraleSupélec - Laboratoire MSSMat
% DICA - Politecnico di Milano
% Copyright 2016_
%% *NOTES*
% _syn2ann_plot_res_station_both_: function to plot syn2ann results at each
% station with both sp96 and exsim hybridization
%% *N.B.*
% Need for:
% _syn2ann_plot_compare.m_

global pfg xlm xlb xtk ylm ylb ytk grd scl mrk tit utd

st = bhr.nm{mm_};
fprintf('%s-with HYBRID\n',bhr.nm{mm_});
dlg = cell(3,1);
dlg{1} = 'EW';
dlg{2} = 'NS';
dlg{3} = 'UD';

for j_ = 1:numel(cpp)
    %% *POST-PROCESS - NUMERICAL SIMULATIONS VS RECORDS*
    
    fn = fullfile(sp,sprintf('%s_sim_rec_%s',st,ann.mtd.scl));
    % all
    set(0,'defaultaxescolororder',clr0);
    syn2ann_plot_compare(...
        ones(5,1),...
        {rec.org,nss.org},...
        mm_,dlg(j_),...
        {'REC';'PBS'},...
        (cpp{j_}),bhr.nm{mm_},...
        fn,...
        [0,vtm_shift(2)]);
    
    % psa
    fn = fullfile(sp,sprintf('%s_sim_sp96_hyb_%s',st,ann.mtd.scl));
    set(0,'defaultaxescolororder',clr12);
    syn2ann_plot_compare(...
        [1 0 0 0 0],...
        {rec.org;nss.hyb.sps;sps.hyb;hbs.sps},...
        mm_,dlg(j_),...
        {'REC';'PBS';'SP96';'HYB'},...
        (cpp{j_}),bhr.nm{mm_},...
        fn,...
        vtm_shift(2)*ones(5,1),...
        {'none','none','none','none','none'},...
        {'-','--','--','-'});
    
    %% *POST-PROCESS - HYBRIDS vs ANN vs SPECTRAL MATCHED*
    
    fn = fullfile(sp,sprintf('%s_hyb_ann_both_%s',st,ann.mtd.scl));
    set(0,'defaultaxescolororder',clr21);
    syn2ann_plot_compare(...
        [1 0 0 0 0],...
        {rec.org;trs.sps.(cpp{j_});spm.sps.(cpp{j_});spm.exs.(cpp{j_});},...
        mm_,dlg(j_),...
        {'REC';'ANN';'SPM-SP96';'SPM-EXSIM'},...
        (cpp{j_}),bhr.nm{mm_},...
        fn,...
        zeros(4,1),...
        {'none';'o';'none';'none'},...
        {'-';'none';'--';'--'});
end