%% *SET-UP*
syn2ann_setup;
global pfg xlm xlb xtk ylm ylb ytk grd scl mrk tit utd
bhr = syn2ann_bhr_parser(bhr);
cd(wd);close all;
mm_ = 1;
cpp = {'e';'n';'z'};
clr = [rgb('Navy');rgb('Navy');...
    rgb('Tomato');rgb('Tomato');...
    rgb('DeepSkyBlue');rgb('DeepSkyBlue')];
set(0,'defaultaxescolororder',clr);

%
% * _PSEUDO-ACCELERATION RESPONSE SPECTRA_
%
pfg.psa = [0 0 16 16];
xlm.psa = {10.^([log10(0.05),1])};
ylm.psa = {10.^(1:3:4)};
xtk.psa = {10.^([log10(0.05),-1:1])};
ytk.psa = {10.^(1:4)};
xlb.psa = {'T [s]'};
ylb.psa = {'PSA [cm/s^2]','',''};
scl.psa = {'log','log','log'};
grd.psa = {'minor'};
mrk.psa = {'none'};
tit.psa = {'PSEUDO-ACCELERATION SPECTRUM (5%)'};
utd.psa = 100;

%% *RESULTS BY CLASS*
als = load(fullfile(wd,'syn2ann_res_ALL.mat'));
abs = load(fullfile(wd,'syn2ann_res_AB.mat'));
cds = load(fullfile(wd,'syn2ann_res_CD.mat'));

%% *POST-PROCESS - SPECTRAL MATCHING vs ANN*
for i_ = 1:numel(mm_)
    st = bhr.nm{mm_(i_)};
    for j_ = 1:numel(cpp)
        fn = fullfile(sp,sprintf('%s_spm_ann_scc',st));
        syn2ann_plot_compare(...
            [1 0 0 0 0],...
            {als.spm.(cpp{j_});...
            als.trs.(cpp{j_});...
            abs.spm.(cpp{j_});...
            abs.trs.(cpp{j_});...
            cds.spm.(cpp{j_});...
            cds.trs.(cpp{j_})},...
            mm_(i_),...
            {'ALL';'';'AB';'';'CD';''},...
            (cpp{j_}),...
            fn,...
            zeros(6,1),...
            {'none';'none';...
            'none';'none';...
            'none';'none'},...
            {'-';'none';...
            '-';'none';...
            '-';'none'});
    end
end